### ISSUE TITLE
"Upload to S3" contains incorrect JSON

### ISSUE THREAD

**Issue by cjmeyer-polymorph** [journeyapps/pdf-reports#13]
in the Readme, in the const result under "Upload to S3", the parameter given to the function is a JSON object, but the second key-value pair doesn't have a key, only a value {name: 'test1.pdf', ...BASE_UPLOAD_CONFIG}
So this is a syntax error

**Comment by rkistner** [comment]
Thanks, fixed the syntax issues in the readme now.
